version: "3.9"
services:

  mysql:
    image: mysql:8
    networks:
      backend:
        ipv4_address: "172.20.0.10"
    restart: on-failure
    command:
      - --mysql-native-password=ON
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  web:
    build: 
      context: .
      dockerfile: Dockerfile.python
    image: cr.yandex/crp7n8uqolgnk4d9cn5a/python:cpa
    restart: on-failure 
    networks:
      backend:
        ipv4_address: "172.20.0.5"
    env_file:
      - .env
    environment:
      - DB_HOST=mysql
      - DB_USER=${MYSQL_USER}
      - DB_PASSWORD=${MYSQL_PASSWORD}
      - DB_NAME=${MYSQL_DATABASE}
    depends_on:
      mysql:
        condition: service_start
    ports:
      - "8090:5000"
  
volumes:
  db_data:

networks:
  backend:
      driver: bridge
      ipam:
        config:
          - subnet: "172.20.0.0/24"
            gateway: "172.20.0.1"
